SHELL := /bin/zsh

.PHONY: help install sync run-api run-frontend \
	test test-cov lint format format-check mypy check clean \
	alembic-init db-revision db-up db-down

help:
	@echo "Available targets:"
	@echo "  install       Install project dependencies"
	@echo "  sync          Sync lockfile dependencies to .venv"
	@echo "  run-api       Run FastAPI app (uvicorn)"
	@echo "  run-frontend  Run Streamlit frontend"
	@echo "  test          Run tests"
	@echo "  test-cov      Run tests with coverage report"
	@echo "  lint          Run ruff lint checks"
	@echo "  format        Format code with ruff"
	@echo "  format-check  Check formatting without changes"
	@echo "  mypy          Run static type checks"
	@echo "  check         Run lint + format-check + mypy + tests"
	@echo "  clean         Remove Python cache files"
	@echo ""
	@echo "Alembic (after Step 10 setup):"
	@echo "  alembic-init  Create alembic scaffold in backend/alembic"
	@echo "  db-revision   Create autogenerated migration (MSG='...')"
	@echo "  db-up         Upgrade database to latest revision"
	@echo "  db-down       Downgrade database by one revision"

install:
	uv sync --all-groups

sync:
	uv sync --all-groups

run-api:
	uv run uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 --reload

run-frontend:
	uv run streamlit run frontend/app.py

test:
	uv run pytest

test-cov:
	uv run pytest --cov=backend --cov-report=term-missing

lint:
	uv run ruff check .

format:
	uv run ruff format .

format-check:
	uv run ruff format --check .

mypy:
	uv run mypy backend

check: lint format-check mypy test

clean:
	rm -rf .pytest_cache .mypy_cache .ruff_cache
	rm -rf backend/**/__pycache__ backend/**/*.pyc

alembic-init:
	uv run alembic init backend/alembic

db-revision:
	uv run alembic revision --autogenerate -m "$(MSG)"

db-up:
	uv run alembic upgrade head

db-down:
	uv run alembic downgrade -1
