from __future__ import annotations

MODEL_TYPE_PROPHET_ONE_RM = "prophet_one_rm"
MODEL_RUN_STATUS_SUCCESS = "SUCCESS"
MODEL_RUN_STATUS_FAILED = "FAILED"
MODEL_RUN_STATUS_PENDING = "PENDING"

FRESHNESS_FRESH = "FRESH"
FRESHNESS_STALE_DATA = "STALE_DATA"
FRESHNESS_STALE_AGE = "STALE_AGE"

MODEL_MAX_AGE_DAYS = 14

ERROR_NO_MODEL = "NO_MODEL"
ERROR_INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
ERROR_INFERENCE = "INFERENCE_ERROR"
