from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "8ca3cc32c6ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_metrics",
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("body_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("calories_kcal", sa.Integer(), nullable=True),
        sa.Column("sleep_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "body_weight_kg IS NULL OR (body_weight_kg >= 30 AND body_weight_kg <= 300)",
            name=op.f("ck_daily_metrics_body_weight_kg_range"),
        ),
        sa.CheckConstraint(
            "calories_kcal IS NULL OR (calories_kcal >= 500 AND calories_kcal <= 10000)",
            name=op.f("ck_daily_metrics_calories_kcal_range"),
        ),
        sa.CheckConstraint(
            "notes IS NULL OR length(notes) <= 2000", name=op.f("ck_daily_metrics_notes_length")
        ),
        sa.CheckConstraint(
            "sleep_hours IS NULL OR (sleep_hours >= 0 AND sleep_hours <= 24)",
            name=op.f("ck_daily_metrics_sleep_hours_range"),
        ),
        sa.PrimaryKeyConstraint("metric_date", name=op.f("pk_daily_metrics")),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("muscle_group", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("name", name=op.f("uq_exercises_name")),
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_type", sa.String(length=50), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("artifact_path", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SUCCESS', 'FAILED')",
            name=op.f("ck_model_runs_model_run_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_model_runs_exercise_id_exercises"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_index(
        "ix_model_runs_type_exercise",
        "model_runs",
        ["model_type", "exercise_id", sa.text("trained_at DESC")],
        unique=False,
    )
    op.create_table(
        "strength_goals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("target_1rm_kg", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ACHIEVED', 'ARCHIVED')",
            name=op.f("ck_strength_goals_strength_goal_status_allowed"),
        ),
        sa.CheckConstraint(
            "target_1rm_kg > 0 AND target_1rm_kg <= 1000",
            name=op.f("ck_strength_goals_target_1rm_kg_range"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_strength_goals_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strength_goals")),
    )
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_date", sa.Date(), nullable=False),
        sa.Column("split_type", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "split_type IN ('PUSH', 'PULL', 'LEGS', 'OTHER')",
            name=op.f("ck_workout_sessions_split_type_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["workout_date"],
            ["daily_metrics.metric_date"],
            name=op.f("fk_workout_sessions_workout_date_daily_metrics"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sessions")),
    )
    op.create_index("ix_sessions_workout_date", "workout_sessions", ["workout_date"], unique=False)
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("is_warmup", sa.Boolean(), nullable=False),
        sa.Column("calculated_1rm", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("reps >= 1 AND reps <= 100", name=op.f("ck_workout_sets_reps_range")),
        sa.CheckConstraint(
            "rpe IS NULL OR (rpe >= 1 AND rpe <= 10 AND (rpe * 2) = CAST(rpe * 2 AS INTEGER))",
            name=op.f("ck_workout_sets_rpe_range_step"),
        ),
        sa.CheckConstraint("set_number >= 1", name=op.f("ck_workout_sets_set_number_min")),
        sa.CheckConstraint(
            "weight_kg >= 0 AND weight_kg <= 1000", name=op.f("ck_workout_sets_weight_kg_range")
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_workout_sets_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.id"],
            name=op.f("fk_workout_sets_session_id_workout_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sets")),
        sa.UniqueConstraint("session_id", "exercise_id", "set_number", name="uq_set_order"),
    )
    op.create_index(
        "ix_sets_exercise_created", "workout_sets", ["exercise_id", "created_at"], unique=False
    )
    op.create_index("ix_sets_exercise_id", "workout_sets", ["exercise_id"], unique=False)
    op.create_index("ix_sets_session_id", "workout_sets", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sets_session_id", table_name="workout_sets")
    op.drop_index("ix_sets_exercise_id", table_name="workout_sets")
    op.drop_index("ix_sets_exercise_created", table_name="workout_sets")
    op.drop_table("workout_sets")
    op.drop_index("ix_sessions_workout_date", table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_table("strength_goals")
    op.drop_index("ix_model_runs_type_exercise", table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_table("exercises")
    op.drop_table("daily_metrics")
    # ### end Alembic commands ###
