from __future__ import annotations

GOAL_STATUS_ACTIVE = "ACTIVE"
GOAL_STATUS_ACHIEVED = "ACHIEVED"
GOAL_STATUS_ARCHIVED = "ARCHIVED"

GOAL_STATUSES = (
    GOAL_STATUS_ACTIVE,
    GOAL_STATUS_ACHIEVED,
    GOAL_STATUS_ARCHIVED,
)

USER_SETTABLE_GOAL_STATUSES = (
    GOAL_STATUS_ACTIVE,
    GOAL_STATUS_ARCHIVED,
)
